Updating Japanese localization
Adventech/sabbath-school-android pull request #90
Opened 2019-03-03 02:46 UTC by imasaru

2019-03-10 16:59 UTC, imasaru commented
@VitalikL 😄

2019-03-29 03:04 UTC, ryonakano requested changes

2019-03-29 03:04 UTC, ryonakano commented on app/src/main/res/values-ja/strings.xml
> +    <string name="ss_login_failed">"ログインするのが失敗しました。もう一度試みて下さい。"</string>
```suggestion
    <string name="ss_login_failed">"ログインに失敗しました。もう一度お試しください"</string>
```
* "ログインするのが失敗" sounds weird for me. It should be "ログインするのに失敗" or, simply "ログインに失敗".
* "試みる" and "試す" has same meaning "try", but I think the latter may be better, because the string "try again" is translated as "もう一度お試しください" in many other software or services (see [the consequence of "もう一度お試しください" in Google Image Search](https://www.google.co.jp/search?q=%E3%82%82%E3%81%86%E4%B8%80%E5%BA%A6%E3%81%8A%E8%A9%A6%E3%81%97%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84&source=lnms&tbm=isch&sa=X&ved=0ahUKEwinspKdq6bhAhWBH3AKHe1XCOUQ_AUIDigB&biw=1920&bih=978))
* This is so tiny thing, but actually "ください" and "下さい" has different meanings, although the pronunciation is same. The former means an formal request ("Please…"), while the latter means "give something to me".
* This sentence seems to have no period:
https://github.com/Adventech/sabbath-school-android/blob/6dc15809f3c5f4826b9711fbb788317091a20a0d/app/src/main/res/values/strings.xml#L48

2019-03-29 03:04 UTC, ryonakano commented on app/src/main/res/values-ja/strings.xml
> +    <string name="ss_quarterlies_filter_languages_prompt_title">"他のの言語で読む"</string>
```suggestion
    <string name="ss_quarterlies_filter_languages_prompt_title">"他の言語で読む"</string>
```
This translation has an extra "の".

2019-03-29 03:04 UTC, ryonakano commented on app/src/main/res/values-ja/strings.xml
> +    <string name="ss_quarterlies_filter_languages_prompt_description">"フィルターボタンをタップして全ての使用可能の言語を見る"</string>
```suggestion
    <string name="ss_quarterlies_filter_languages_prompt_description">"フィルターボタンをタップして全ての使用可能な言語を見る"</string>
```
"Available" is adjective, so the translation should be "利用可能**な**".

2019-03-31 19:35 UTC, VitalikL approved these changes

2019-03-31 19:35 UTC, merged

2019-04-01 04:37 UTC, imasaru commented
@ryonakano 遅く答えてすいません! I just saw you in my notifications and ran to my computer. 訂正ありがとう。コメントをすべて読んだ！

Thank you for helping me with my Japanese. より小さい間違いも正して**く**ださい！